-- 0053_user_visits: two timestamps per user, so the app can tell a returning
-- reader what happened while they were away.
--
-- The "what's new" panel needs a reference point: a moment in the past such that
-- everything created after it is news to *this* user. A session cannot supply it
-- (a session slides for days and survives a reload), and "last login" cannot
-- either (a cookie that never expires means one login a year). So the reference
-- is kept on the account itself, as two columns.
--
-- last_seen_at is a heartbeat: the summary endpoint stamps it to now() on every
-- read. Because a reload or a walk around the app re-reads the summary, it keeps
-- moving for as long as the reader is here.
--
-- visit_reference_at is the reference point itself — the "since" of the digest —
-- and it moves only when a *new visit* begins, which is defined as a gap of at
-- least whatsnew.VisitGap (6 h) between two reads. On that transition it takes
-- the old last_seen_at: the last moment the reader was demonstrably present in
-- the previous visit. Within one visit it never moves, which is exactly the
-- "refreshing must not reset the panel" requirement — the digest a reader sees
-- at 9:00 is the same digest at 9:40, having read the same rows.
--
-- Both are NULL for an account that has never asked for a summary. A NULL
-- visit_reference_at is what makes a first-ever visit show nothing: there is no
-- "away" to report on, and a brand-new user does not want the whole library
-- announced as news.
--
-- Neither column touches updated_at. Being here is not a change to the profile,
-- and the user-management screens must not start showing every account as
-- "edited" the moment somebody opens the library.

ALTER TABLE users
    ADD COLUMN last_seen_at        TIMESTAMPTZ,
    ADD COLUMN visit_reference_at  TIMESTAMPTZ;

-- The summary's counting queries are all "rows created after a timestamp", run
-- once per library-home load. Each gets an index ordered the way the query reads
-- it, so the work is proportional to what is new rather than to the size of the
-- table.
--
-- photos needs no new index: idx_photos_live_created_at (0015) already covers
-- (created_at DESC) partial on archived_at IS NULL, which is the same range the
-- summary counts over.

-- Newly created albums. Partial on the hand-curated type: folder/moment/month/
-- state albums are generated by the machine (an import can mint hundreds in one
-- go) and are not news anybody wants read out to them.
CREATE INDEX idx_albums_created_at ON albums (created_at DESC)
    WHERE type = 'album';

-- Newly named people. Partial on a non-empty name for the same reason the panel
-- filters on it: an unnamed subject is work in progress, not an announcement.
CREATE INDEX idx_subjects_created_at ON subjects (created_at DESC)
    WHERE name <> '';

-- New comments. The existing idx_photo_comments_photo is keyed by photo first,
-- so it cannot serve a library-wide "since" range; this one can, and stays
-- partial on the live rows exactly as its sibling does.
CREATE INDEX idx_photo_comments_created_at ON photo_comments (created_at DESC)
    WHERE deleted_at IS NULL;
